name: Deploy to Hetzner Server

# Trigger deployment on push to the main branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code from GitHub
      uses: actions/checkout@v3

    - name: Set up SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        ssh-passphrase: ${{ secrets.SSH_PASSPHRASE }}

    - name: Deploy to Hetzner server
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
          cd /home/cheloo/eat-me || exit 1
          git pull origin main || exit 1
          # Optional: Run build or other tasks (e.g., pip install, npm install)
          sudo systemctl restart nginx || exit 1
          sudo systemctl restart eat-me.service || exit 1
        EOF
      env:
        SERVER_USER: ${{ secrets.SERVER_USER }}
        SERVER_IP: ${{ secrets.SERVER_IP }}

    - name: Check deployment status
      run: echo "Deployment successful!"
